import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

interface CategoryData {
  name: string;
  value: number;
  percentage: number;
  emoji: string;
}

interface ExportData {
  type: 'expense' | 'income';
  period: string;
  total: number;
  categories: CategoryData[];
  chartElement?: HTMLElement;
}

export const exportToPDF = async (data: ExportData) => {
  const { type, period, total, categories, chartElement } = data;
  const doc = new jsPDF('p', 'mm', 'a4');
  
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  let yPos = margin;

  // Header
  doc.setFillColor(type === 'expense' ? 239, 68, 68 : 34, 197, 94);
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text(`${type === 'expense' ? 'Expense' : 'Income'} Report`, margin, 20);
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  const date = new Date().toLocaleDateString('en-IN', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  });
  doc.text(`Generated on: ${date}`, margin, 30);
  doc.text(`Period: ${period}`, margin, 36);

  yPos = 55;

  // Summary Section
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Summary', margin, yPos);
  yPos += 10;

  doc.setFillColor(248, 250, 252);
  doc.roundedRect(margin, yPos - 5, pageWidth - 2 * margin, 20, 3, 3, 'F');
  
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(type === 'expense' ? 220, 38, 38 : 22, 163, 74);
  doc.text(`Total ${type === 'expense' ? 'Expenses' : 'Income'}:`, margin + 5, yPos + 5);
  doc.text(`₹${total.toLocaleString('en-IN')}`, pageWidth - margin - 5, yPos + 5, { align: 'right' });
  
  yPos += 30;

  // Category Breakdown
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Category Breakdown', margin, yPos);
  yPos += 8;

  // Table Header
  doc.setFillColor(241, 245, 249);
  doc.rect(margin, yPos, pageWidth - 2 * margin, 10, 'F');
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(71, 85, 105);
  doc.text('Category', margin + 5, yPos + 7);
  doc.text('Amount', pageWidth - margin - 40, yPos + 7);
  doc.text('Percentage', pageWidth - margin - 5, yPos + 7, { align: 'right' });
  
  yPos += 10;

  // Category Rows
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(0, 0, 0);
  
  categories.forEach((category, index) => {
    // Check if we need a new page
    if (yPos > pageHeight - 40) {
      doc.addPage();
      yPos = margin;
    }

    // Alternate row colors
    if (index % 2 === 0) {
      doc.setFillColor(249, 250, 251);
      doc.rect(margin, yPos, pageWidth - 2 * margin, 8, 'F');
    }

    doc.setFontSize(10);
    doc.text(`${category.emoji} ${category.name}`, margin + 5, yPos + 6);
    doc.text(`₹${category.value.toLocaleString('en-IN')}`, pageWidth - margin - 40, yPos + 6);
    doc.setFont('helvetica', 'bold');
    doc.text(`${category.percentage}%`, pageWidth - margin - 5, yPos + 6, { align: 'right' });
    doc.setFont('helvetica', 'normal');
    
    yPos += 8;
  });

  // Add chart if provided
  if (chartElement) {
    try {
      // Check if we need a new page for the chart
      if (yPos > pageHeight - 120) {
        doc.addPage();
        yPos = margin;
      } else {
        yPos += 10;
      }

      doc.setFontSize(16);
      doc.setFont('helvetica', 'bold');
      doc.text('Visual Distribution', margin, yPos);
      yPos += 5;

      const canvas = await html2canvas(chartElement, {
        scale: 2,
        backgroundColor: '#ffffff',
        logging: false,
      });
      
      const imgData = canvas.toDataURL('image/png');
      const imgWidth = pageWidth - 2 * margin;
      const imgHeight = (canvas.height * imgWidth) / canvas.width;
      
      doc.addImage(imgData, 'PNG', margin, yPos, imgWidth, Math.min(imgHeight, 100));
    } catch (error) {
      console.error('Error adding chart to PDF:', error);
    }
  }

  // Footer
  const footerY = pageHeight - 15;
  doc.setFontSize(8);
  doc.setTextColor(100, 116, 139);
  doc.setFont('helvetica', 'italic');
  doc.text('Generated by NeuraDesk Finance Manager', pageWidth / 2, footerY, { align: 'center' });
  doc.text(`Page ${doc.getCurrentPageInfo().pageNumber}`, pageWidth - margin, footerY, { align: 'right' });

  // Save the PDF
  const fileName = `${type}-report-${period.toLowerCase().replace(/\s+/g, '-')}-${Date.now()}.pdf`;
  doc.save(fileName);
};
